# Generated by Django 5.0.6 on 2024-07-03 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('notice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255, unique=True)),
                ('countries', models.ManyToManyField(to='FDRADMIN.country')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.district')),
            ],
        ),
        migrations.CreateModel(
            name='ClubReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='club_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.club')),
                ('rotary_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.rotaryyear')),
            ],
        ),
        migrations.CreateModel(
            name='ClubBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.club')),
                ('rotary_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.rotaryyear')),
            ],
        ),
        migrations.CreateModel(
            name='RotaryYearFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin_files/')),
                ('rotary_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='FDRADMIN.rotaryyear')),
            ],
        ),
    ]
