# Generated by Django 5.0.6 on 2024-07-03 19:27

import FDRADMIN.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDRADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaryyearfile',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotaryyearfile',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotaryyearfile',
            name='file',
            field=models.FileField(upload_to='rotary_year_files/', validators=[FDRADMIN.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='rotaryyearfile',
            name='rotary_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRADMIN.rotaryyear'),
        ),
    ]
