# Generated by Django 5.0.6 on 2024-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDRADMIN', '0002_rotaryyearfile_is_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaryyearfile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotaryyearfile',
            name='decline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
