# Generated by Django 5.0.6 on 2024-07-03 19:58

import FDRADMIN.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDRADMIN', '0003_rotaryyearfile_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubreport',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='clubreport',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='rotaryyearfile',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='rotaryyearfile',
            name='decline_date',
        ),
        migrations.RemoveField(
            model_name='rotaryyearfile',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='rotaryyearfile',
            name='is_declined',
        ),
        migrations.AddField(
            model_name='clubreport',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubreport',
            name='decline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubreport',
            name='file',
            field=models.FileField(default=1, upload_to='club_reports/', validators=[FDRADMIN.models.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubreport',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotaryyearfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rotaryyear',
            name='notice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rotaryyear',
            name='year',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
